### ISSUE TITLE
innerHeight on iPhone X

### ISSUE THREAD

**Issue by wushan** [tylerjpeterson/ios-inner-height#2] opened 2017-12-15 01:38 UTC
Hi there, 
I was testing this amazing tool on iPhone X, but it seems not working, the innerHeight I got is still contains the url bar on the top and toolbar at the bottom, which more likely is `deviceHeight`, haven't tested on other ios devices I will report here when I do.

Maybe providing an real working example for this module ?

**Comment by tylerjpeterson** [comment] 2017-12-15 06:35
Hi @wushan -

It seems to work fine for me on iPhone X (see screenshot below). The screen on the left is what renders when the page is initially loaded. The screen on the right shows the result of scrolling down the page. In the left image, the measurement reported by this module is the full viewport height as expected (748px). It remains so after scrolling (right). Compare that to what the browser reports when requesting `window.innerHeight` (the bottom label). 

If you are seeing different results, please let me know how to reproduce and I can work to find a fix. I'll try to get an example up soon to better demonstrate the intended functionality. Thanks.

![example](https://94012cf9.s3.amazonaws.com/output.png)

**Comment by tylerjpeterson** [comment] 2017-12-19 10:24
Closing - but feel free to re-open if my explanation isn't accurate.

**Closed by tylerjpeterson** 2017-12-19 10:24 UTC

**Comment by usb248** [comment] 2020-09-07 11:56
Still doesn't work on iphone 11 pro & safari browser.
